chore(templates): Use fully qualified nixpkgs URL
nickel-lang/organist pull request #196
Opened 2024-04-21 05:28 UTC by srid

This is necessary to be able to use this flake on systems with empty Nix registry.

2024-04-21 05:32 UTC, YorikSar requested changes
Please update `flake.lock` accordingly.

2024-04-21 09:33 UTC, srid commented
@YorikSar Which `flake.lock`? The template [does not have one](https://github.com/srid/organist/tree/patch-1/templates/default).

2024-04-22 07:40 UTC, YorikSar approved these changes
Ah, good point, I misunderstood which flake is involved here.

2024-04-22 09:32 UTC, thufschmitt approved these changes
Thanks

2024-04-22 09:38 UTC, merged